export { default as Navbar } from "./Navbar";
export { default as Home } from "./Home";
export { default as Photography } from "./Photography";
export { default as Projects } from "./Projects";
export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as Background } from "./Background";
export { default as Interests } from "./Interests";
export { default as Goals } from "./Goals";
